stages:
  - benchmark
  - benchmark-completion

.scripts:
   build-ruby: &RUBY_BUILD |
     ./autogen.sh
     mkdir -p build
     cd build
     ../configure --disable-jit-support --disable-install-doc
     make
     cd ..

# Run Benchmarks
benchmark1:
  stage: benchmark
  tags: [yuria]
  script:
    - *RUBY_BUILD
    
    # back to the harddisk so that rebench can read the version details
    - cd faststart
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria

# Run Benchmarks
benchmark2:
  stage: benchmark
  tags: [yuria2]
  script:
    - *RUBY_BUILD

    # back to the harddisk so that rebench can read the version details
    - cd faststart
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark-micros
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria2

# Run Benchmarks
benchmark3:
  stage: benchmark
  tags: [yuria3]
  script:
    - *RUBY_BUILD
    
    # back to the harddisk so that rebench can read the version details
    - cd faststart
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf benchmark     m:yuria3

report-completion:
  stage: benchmark-completion
  tags: [yuria]
  script:
    - cd faststart
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion rebench.conf
